set1 = {'A', 'P', 'P', 'L', 'E'}
print(set1)
set2 = set(list("PINEAPPLE"))
print(set2)
set3 = set(list('BANANA'))
print(set3)
print(set1 | set2)
print(set1 & set2)
print(set1 ^ set2)
set3.add('X')
print(set3)
set3.add('Y')
print(set3)
set4 = set()
